language: php

dist: trusty

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

env:
  - SYMFONY_VERSION=5.0.*
  - SYMFONY_VERSION=5.1.*

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - composer self-update
  - composer require --no-update symfony/form ${SYMFONY_VERSION}

install:
  - composer install --no-interaction --prefer-dist
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.2/php-coveralls.phar

before_script:
  - mkdir -p build/logs

script:
  - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php coveralls.phar -v
